replicaCount: 2

image:
  repository: ghcr.io/sirajmoideen/uptime-monitor
  tag: fbe8276ca6d586e9ef022d2847f64de25ef9b376
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

ingress:
  host: uptime.local