apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-monitor

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: uptime-monitor

  template:
    metadata:
      labels:
        app: uptime-monitor

    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}

      containers:
      - name: uptime-monitor

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.containerPort }}

        envFrom:
        - secretRef:
            name: {{ .Values.secretName }}