apiVersion: v1
kind: Service
metadata:
  name: uptime-monitor

spec:
  selector:
    app: uptime-monitor

  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}

  type: ClusterIP