replicaCount: 1

image:
  repository: ghcr.io/sirajmoideen/uptime-monitor
  tag: 87928e2bb8f0d6a84186c15d671f747e573cf975
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

containerPort: 5000

ingress:
  host: uptime-dev.local
