replicaCount: 1

image:
  repository: ghcr.io/sirajmoideen/uptime-monitor
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

containerPort: 5000

ingress:
  host: uptime-dev.local
